services:
  web:
    build: .
    ports:
      - "8818:8000"
    volumes:
      - .:/app
    command: uv run python manage.py runserver 0.0.0.0:8000
    networks:
      - webapp

networks:
  webapp:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.1/16
